'project_id': '813246'
'base_path': '.'
'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true

files:
  [
    {
      'source': 'src/locales/text/zh-Hans/**/*.*',
      'translation': 'src/locales/text/%locale%/%original_file_name%'
    }
  ]
